title: <p align="center"> Venkat Swamy Mannam </p>
![Logo](/assets/img/logo.jpg)

description:
  <p align="center">
   
  <br>   
  I'm working as Data Visualisation and Business insight anlyst.
  Also now learnign the Python, Machine Learning and AI in upgrad.
  <br>
  </p>
